### ISSUE TITLE
Seems like this file is corrupted and cannot be extracted

### ISSUE THREAD

**Issue by Boring545** [supersven/ghc-riscv-bindist#1]

**Comment by Boring545** [comment]
```
$ tar -zxvf ghc-9.10.1-riscv64-unknown-linux.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

```

**Comment by supersven** [comment]
@Boring545 This file is managed by Git LFS. You may want to check the file size in your checkout (or download it as *raw* file in the GitHub UI.)

N.B. this is not an official bindist! Actually, it's a build of this branch: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12783

I'd be happy to get feedback / bug reports for this build; However, please be aware that there may be weird bugs. I created this bindist for testing this branch.

**Comment by Boring545** [comment]
I think the problem may be my network issue. The files downloaded through the browser can be decompressed normally. In fact, I did the same yesterday, but failed.
Thank you for your reply.

**Comment by Boring545** [comment]
I’m configuring Haskell-related tools on RISC-V architecture and am trying to install Cabal. Some members of the Cabal community advised me to run a bootstrap script to complete the Cabal compilation process. However, this script has been running for 20 hours without finishing. Is there a better method?
